---
title: "Introduction to Programming"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This section introduces us to R by using it as a simple calculator

Assigning Variables 
```{r}
Result <- 15 + 25.1 + 20.25

Second_Result <- 12 + 22.6 + 68
```

New Functions 
```{r}
years_old <- 25.7
```

Rounds up
```{r}
round(years_old)
```

Rounds down
```{r}
floor(years_old) 

years_old <- 25.765
```

Comma after the object to specify argument
```{r}
round (years_old, 2)

Bill_age <- "Bill is 25.7 years old"

Bill_age <- paste('Bill is', years_old)
```

# Misconceptions

Variables in programs do not work the same way as they do in spreadsheets
```{r}
grade <- 55
total <- grade + 10
print (total)
grade <- 90
print (total) # value of total in a spreadsheet will be 100, but in programming a variable holds the value it was assigned (65)
total <- grade + 10
print (total) # executed in the way it was defined
```

What will this code do?
```{r}
p <- 2
z <- 5
out <- p * z  # What should the value of out be?
print (out) # What is the value of out? Is it the same as expected?

my_quiz <- c("uno",
             "dos",
             "tres",
             "cuatro", #"," was missing after cuatros
             "cinco")
print (my_quiz) #quiz was spelled wrong
str(my_quiz)
length(my_quiz) #len function does not exist; write full length to get function

my_numeric_variable = 4.2
class(my_numeric_variable)
typeof(my_numeric_variable)
length(my_numeric_variable)
attributes(my_numeric_variable)

list("uno", "dos",'...')

y <- c(1, 2, 3)
z <- c("Sarah", "Tracy", "Jon")
class(z)
class(y)

x <- list(1, "a", TRUE)
x
x[[2]]

my_dataframe <- data.frame (no = c(1,2,3), c("Tracey", "John", "Pete"), c(TRUE, FALSE, TRUE))
my_dataframe
str (my_dataframe)
```
